name: pdfconverter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.15
  pdf: ^3.10.7
  google_mlkit_text_recognition: ^0.11.0
  image: ^4.1.3
  dio: ^5.4.0
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  pdf_render: ^1.4.0
  syncfusion_flutter_pdf: ^24.2.8
  # New dependencies for PDF signing
  flutter_pdfview: ^1.3.2
  signature: ^5.4.1
  shared_preferences: ^2.2.2
  flutter_signature_pad: ^3.0.1
  overlay_support: ^2.1.0
  url_launcher: ^6.3.1
  share_plus: ^10.0.0
  in_app_review: ^2.0.10
  get_it: ^8.0.3
  permission_handler: ^11.3.0
  cunning_document_scanner: ^1.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.5
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon2.png"
  adaptive_icon_background: "assets/icon3.png"

flutter:
  uses-material-design: true
  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic


